# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14RPVHY90SglqQ7QpeCNLnD8W_7U8Htj-
"""

import streamlit as st
import numpy as np
import itertools
import matplotlib.pyplot as plt
from shapely.geometry import Polygon

# ======================================================
# FUNÇÃO PRINCIPAL: MÉTODO GRÁFICO
# ======================================================

def metodo_grafico(c, A, b, sinal, maximize=True):
    vertices = []

    # interseções entre pares de restrições
    for i, j in itertools.combinations(range(len(A)), 2):
        A_ = np.array([A[i], A[j]])
        b_ = np.array([b[i], b[j]])
        if np.linalg.det(A_) != 0:
            vertices.append(np.linalg.solve(A_, b_))

    # interseções com eixos
    for Ai, bi in zip(A, b):
        if Ai[0] != 0:
            vertices.append(np.array([bi / Ai[0], 0]))
        if Ai[1] != 0:
            vertices.append(np.array([0, bi / Ai[1]]))

    vertices.append(np.array([0.0, 0.0]))   # incluir origem

    # factibilidade
    def factivel(v):
        if v[0] < -1e-8 or v[1] < -1e-8:
            return False
        for Ai, bi, s in zip(A, b, sinal):
            lhs = Ai @ v
            if s == "<=" and lhs > bi + 1e-8: return False
            if s == ">=" and lhs < bi - 1e-8: return False
        return True

    factiveis = [v for v in vertices if factivel(v)]
    if len(factiveis) == 0:
        return None, None, None, None

    pts = np.array(factiveis)
    centro = pts.mean(axis=0)

    def angulo(p):
        return np.arctan2(p[1] - centro[1], p[0] - centro[0])

    pts_ordenados = pts[np.argsort([angulo(p) for p in pts])]

    valores = [c @ v for v in pts_ordenados]
    idx = np.argmax(valores) if maximize else np.argmin(valores)
    otimo = pts_ordenados[idx]
    valor_otimo = valores[idx]

    return pts_ordenados, valores, otimo, valor_otimo


# ======================================================
# FRONT-END STREAMLIT
# ======================================================

st.title("Método Gráfico para Programação Linear")
st.write("### Interface Interativa – Região Factível + Função Objetivo")

st.sidebar.header("Parâmetros do Problema")

# ------------------------------------
# Entrada FO
# ------------------------------------
c_input = st.sidebar.text_input("Função Objetivo (ex: 3,5)", "3,5")
c = np.array([float(x) for x in c_input.split(",")])

# ------------------------------------
# Entrada restrições
# ------------------------------------
st.sidebar.write("### Matriz A (uma linha por restrição)")
A_input = st.sidebar.text_area("A:", "1,1\n3,1")
A = np.array([[float(x) for x in row.split(",")] for row in A_input.split("\n")])

b_input = st.sidebar.text_input("Vetor b (ex: 6,9)", "6,9")
b = np.array([float(x) for x in b_input.split(",")])

sinal_input = st.sidebar.text_input("Sinais (ex: <=,<=)", "<=,<=")
sinal = sinal_input.split(",")

maximize = st.sidebar.selectbox("Tipo de otimização", ["Maximizar", "Minimizar"])
maximize_bool = maximize == "Maximizar"

# ----------------------------------------------------
# Calcular solução
# ----------------------------------------------------
if st.button("Resolver Problema"):

    pts, valores, otimo, valor_otimo = metodo_grafico(c, A, b, sinal, maximize_bool)

    if pts is None:
        st.error("❌ Não existe região factível.")
    else:
        st.success(f"Ótimo encontrado em: {otimo}, valor FO = {valor_otimo}")

        # ================================
        # GRÁFICO
        # ================================
        fig, ax = plt.subplots(figsize=(8,6))

        # limites
        xmax = max(max(b), max(pts[:,0])) + 1
        ymax = max(max(b), max(pts[:,1])) + 1
        xs = np.linspace(0, xmax, 400)

        # restrições
        for i, (Ai, bi) in enumerate(zip(A, b)):
            if Ai[1] != 0:
                x2 = (bi - Ai[0]*xs) / Ai[1]
                ax.plot(xs, x2, label=f"Restrição {i+1}")

        # região factível
        poly = Polygon(pts)
        xp, yp = poly.exterior.xy
        ax.fill(xp, yp, alpha=0.3, color="lightgreen", label="Região factível")

        # vértices
        ax.scatter(pts[:,0], pts[:,1], color="red", s=60, label="Vértices")

        # ótimo
        ax.scatter(otimo[0], otimo[1], color="blue", s=80, label="Ótimo")

        # função objetivo tracejada
        if c[1] != 0:
            fo_line = (valor_otimo - c[0]*xs) / c[1]
            ax.plot(xs, fo_line, "k--", linewidth=2, label="Função Objetivo")

        ax.set_xlim(-1, xmax)
        ax.set_ylim(-1, ymax)
        ax.set_xlabel("$x_1$")
        ax.set_ylabel("$x_2$")
        ax.legend()
        ax.grid(True)
        ax.set_title("Método Gráfico – Solução e Região Factível")

        st.pyplot(fig)

        # ================================
        # Mostrar tabela de resultados
        # ================================
        st.write("### Vértices e valores da função objetivo")
        tabela = {"x1": pts[:,0], "x2": pts[:,1], "FO": valores}
        st.table(tabela)